[package]
name = "graphql-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
async-graphql = "7.0"
async-graphql-axum = "7.0"
mongodb = "2.8"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"