version: '3.8'

services:
  graphql-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql-rust-api
    restart: always
    ports:
      - "4000:4000"
    environment:
      - RUST_ENV=production
      - HOST=0.0.0.0
      - PORT=4000
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=graphql_rust_db
    networks:
      - graphql_rust_network

networks:
  graphql_rust_network:
    external: true
